routes/web.php
<?php
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::get('home', function () {
    return view('welcome');
})->name('welcome');

Route::get('/', 'Frontend\TaskController@index')->name('home');

// Route::get('/', 'HomeController@index');
// Route::get('page/{page?}', 'HomeController@index');
Route::get('setting1', 'SettingController@index');
// Route::get('setting2', 'Admin\SettingController@index');
// Route::get('setting3', 'Admin\Test\SettingController@index');

Route::group(['namespace' => 'Admin'] , function(){
	Route::get('dashboard', 'DashboardController@index');
	Route::get('setting2', 'SettingController@index')->name('setting2');
	Route::get('setting3', 'Test\SettingController@index');
});

Route::get('task/complete/{id}' , function($id){
	dd('Hoàn thành '.$id);
})->name('todo.task.complete');

Route::get('task/reset/{id}' , function($id){
	dd('Làm lại '.$id);
})->name('todo.task.reset');

//route group cách 1
Route::group(['prefix' => 'task'] , function(){
	Route::get('complete/{id}' , function($id){
		dd('Hoàn thành '.$id);
	})->name('todo.task.complete');
	Route::get('reset/{id}' , function($id){
		dd('Làm lại '.$id);
	})->name('todo.task.reset');
});

//route group cách 2
Route::prefix('task')->group(function(){
	Route::get('complete/{id}' , function($id){
		dd('Hoàn thành '.$id);
	})->name('todo.task.complete');

	Route::get('reset/{id}' , function($id){
		dd('Làm lại '.$id);
	})->name('todo.task.reset');
});

Route::get('list' , function(){
	 $list = [
        [
            'name' => 'Học View trong Laravel',
            'status' => 0
        ],
        [
            'name' => 'Học Route trong Laravel',
            'status' => 1
        ],
        [
            'name' => 'Làm bài tập View trong Laravel',
            'status' => -1
        ],
    ];
	return view('list',[
		'list' => $list
	]);
});

Route::get('profile' , function(){
	$name = 'Nguyễn Văn Hòa';
	$birthday = '2000';
	$school = 'PTIT';
	$address = 'Hà Đông -HN';
	$introduce = '<h1>Tên mình là Nguyễn Văn Hòa</h1>
	<h2>Yêu màu hồng</h2>
	<h3>Vui vẻ , hòa đồng</h3>
	<h4>Hay chơi thể thao</h4>
	<h5>Thích nghe nhạc , đi du lịch ....</h5>';
	$goal = 'Lương triệu đô';

	return view('profile',[
		'name' => $name,
		'birthday' => $birthday,
		'school' => $school,
		'address' => $address,
		'introduce' => $introduce,
		'goal' => $goal
	]);
});
// Route::resource('task', 'Frontend\TaskController');
Route::group(['namespace' => 'Frontend','as' => 'task.'] , function(){
	Route::get('task','TaskController@index')->name('index');
	Route::get('task/create','TaskController@create')->name('create');
	Route::post('task/store','TaskController@store')->name('store');
	Route::get('task/{id}','TaskController@show')->name('show');
	Route::get('task/{id}/edit','TaskController@edit')->name('edit');
	Route::put('task/{id}','TaskController@update')->name('update');
	Route::delete('task/{id}','TaskController@destroy')->name('destroy');
	Route::get('task/complete/{id}','TaskController@complete')->name('complete');
	Route::get('task/recomplete/{id}','TaskController@reComplete')->name('recomplete');
});

resources/views/hello2.blade.php
<!-- resources/views/hello2.blade.php-->
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>hello cac ban</title>
    <link rel="stylesheet" href="">
</head>
<body>
@if (count($records) === 1)
    Có 1 
@elseif (count($records) > 1)
   Có nhiều
@else
    Không có
@endif
<br>
@foreach ($records as $record)
    {{ $record }} </br>
@endforeach
<p>Tên tôi là: {{ $username }} </p>
<p>Tên tôi là: {{ $name }} </p>
<p>Tên tôi là: {!! $name !!} </p>
<p>Tôi sinh năm {{ $year }}</p>
<p>Tôi sinh năm {{ $school[0] }}</p>
</body>
</html>

resources/views/home.blade.php
@extends('layouts.master')

@section('title')
Laravel Todo - Basic
@endsection

@section('css')
<link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.4.0/css/font-awesome.min.css" rel='stylesheet' type='text/css'>
<link href="https://fonts.googleapis.com/css?family=Lato:100,300,400,700" rel='stylesheet' type='text/css'>
<link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" rel="stylesheet">
<style>
    body {
        font-family: 'Lato';
    }
    .fa-btn {
        margin-right: 1px;
    }
    .task-table tbody tr td:nth-child(2){
        width: 120px;
    }
    .task-table tbody tr td:nth-child(3){
        width: 100px;
    }
    .add-mb{
        margin-bottom: 2%;
    }
</style>
@endsection

@section('script')
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.4/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
@endsection

@section('header')
@include('layouts.header')
@endsection


@section('content')
<div class="container">
    <div class="col-sm-offset-2 col-sm-8">
        <!-- Current Tasks -->
        <a href="{{ route('task.create') }}" class="btn btn-success add-mb">
                <i class="fa fa-plus"> </i> Thêm mới công việc
        </a>
        <div class="panel panel-default">
            <div class="panel-heading">
                Danh sách công việc hiện tại
            </div>

            <div class="panel-body">
                <table class="table table-striped task-table">
                    <thead>
                    <th>Tên công việc</th>
                    <th>Trạng thái</th>
                    <th>Độ ưu tiên</th>
                    <th>&nbsp;</th>
                    </thead>
                    <tbody>
                    @foreach($tasks as $task)
                        <tr>
                        <td class="table-text">
                            <div><a href="{{ route('task.show',$task->id) }}">
                                @if ($task->status != 2)
                                    {{$task->name}}
                                @else
                                    <strike>{{$task->name}}</strike>
                                @endif
                            </a></div></td>
                        <td class="table-text"><div>
                            @switch($task->status)
                                @case(-1)
                                    Không làm
                                    @break
                                @case(0)
                                    Chưa làm
                                    @break
                                @case(1)
                                    Đang làm
                                    @break
                                @default
                                    Đã làm
                            @endswitch
                        </div></td>

                        <td class="table-text"><div>
                            @switch($task->priority)
                                @case(0)
                                    Bình thường
                                    @break
                                @case(1)
                                    Quan trọng
                                    @break
                                @default
                                    Khẩn cấp
                            @endswitch
                        </div></td>
                        <!-- Task Complete Button -->
                        @if($task->status == 2)
                            <td>
                                <a href="{{ route('task.recomplete' , $task->id) }}" type="submit" class="btn btn-success">
                                    <i class="fa fa-repeat"></i> Làm lại
                                </a>
                            </td>
                        @else
                            <td>
                                <a href="{{ route('task.complete' , $task->id) }}" type="submit" class="btn btn-success">
                                    <i class="fa fa-btn fa-check"></i> Hoàn thành
                                </a>
                            </td>
                        @endif

                        @if($task->status != 2)
                            <td>
                                <a href="{{ route('task.edit' , $task->id) }}" type="submit" class="btn btn-primary">
                                    <i class="fa fa-btn fa-pencil"></i> Chỉnh sửa
                                </a>
                            </td>
                        @endif
                        <!-- Task Delete Button -->
                        <td>
                            <form action="{{ route('task.destroy' , $task->id) }}" method="POST">
                                {{ csrf_field() }}
                                {{ method_field('DELETE') }}
                                <button type="submit" class="btn btn-danger">
                                    <i class="fa fa-btn fa-trash"></i> Xoá
                                </button>
                            </form>
                        </td>
                    </tr>
                    @endforeach
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/list.blade.php
<!DOCTYPE html>
<html>
<head>
	<title>List</title>
	<meta charset="utf-8">
  	<meta name="viewport" content="width=device-width, initial-scale=1">
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
	<style type="text/css">
		#my-table{
			width: 60%;
			position: absolute;
			top:50%;
			left: 50%;
			transform: translate(-50%,-50%);
		}
	</style>
</head>
<body>
<table class="table table-bordered" id="my-table">
  <tbody>
    @foreach ($list as $row)
   <tr>
      <th scope="row">{{ $row['name'] }}</th>
      <td>@if ($row['status'] == 1)
              Đã hoàn thành
          @elseif ($row['status'] == -1)
             Không thực hiện
          @else
              Chưa làm
          @endif
      </td>
    </tr>
    @endforeach
    
  </tbody>
</table>
</body>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
</html>

resources/views/profile.blade.php
@extends('layouts.master')

@section('title')
Profile
@endsection
@section('css')
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
  <style type="text/css">
    #my-table{
      width: 60%;
      position: absolute;
      top:50%;
      left: 50%;
      transform: translate(-50%,-50%);
    }
  </style>
@endsection

<!-- <div>
                <a href="{{ route('task.index') }}" type="submit" class="btn btn-success">
                    <i class="fa fa-btn fa-check"></i>index
                </a>
                <a href="{{ route('task.create') }}" type="submit" class="btn btn-success">
                    <i class="fa fa-btn fa-check"></i>create
                </a>
                <a href="{{ route('task.store') }}" type="submit" class="btn btn-success">
                    <i class="fa fa-btn fa-check"></i>store
                </a>
                <a href="{{ route('task.show' , 1) }}" type="submit" class="btn btn-success">
                    <i class="fa fa-btn fa-check"></i>show
                </a>
                <a href="{{ route('task.edit' , 1) }}" type="submit" class="btn btn-success">
                    <i class="fa fa-btn fa-check"></i>edit
                </a>
                <a href="{{ route('task.update' , 1) }}" type="submit" class="btn btn-success">
                    <i class="fa fa-btn fa-check"></i>update
                </a>
                <a href="{{ route('task.delete' , 1) }}" type="submit" class="btn btn-success">
                    <i class="fa fa-btn fa-check"></i>delete
                </a>
            
            </div> -->



@section('content')
<table class="table table-bordered" id="my-table">
  <tbody>
    <tr>
      <th scope="row">Họ tên</th>
      <td>{{ $name }}</td>
    </tr>
    <tr>
      <th scope="row">Năm sinh</th>
      <td>{{ $birthday }}</td>
    </tr>
    <tr>
      <th scope="row">Trường học</th>
      <td>{{ $school }}</td>
    </tr>
    <tr>
      <th scope="row">Quê quán</th>
      <td>{{ $address }}</td>
    </tr>
    <tr>
      <th scope="row">giới thiệu</th>
      <td colspan="2">{!! $introduce !!}</td>
    </tr>
    <tr>
      <th scope="row">Mục tiêu</th>
      <td>{{ $goal }}</td>
    </tr>
  </tbody>
</table>
@endsection


@section('script')
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>

@endsection